name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./Rubicon.Demo.Shared            
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build and Publish Package
      run: dotnet build --configuration Release 
    
    - name: Prep packages
      run: dotnet nuget add source --username jgruppen --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/jgruppen/index.json"
          
    - name: Publish to GitHub Packages
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
      env:
        DOTNET_CLI_APIKEY: ${{ secrets.GITHUB_TOKEN }}
